### ISSUE TITLE
TypeError: localizedTime.tz is not a function

### ISSUE THREAD

**Issue by ronnyandre** [pvoznyuk/react-live-clock#10]
ReactLiveClock.render
node_modules/react-live-clock/lib/Component.js:76
  73 | var localizedTime = (0, _moment2.default)(dateValue);
  74 | 
  75 | if (timezone) {
> 76 |   localizedTime.tz(timezone);
  77 | }
  78 | 
  79 | var formattedTime = localizedTime.format(format);

**Comment by emersonbroga** [comment]
I was able to fix it by changing:
```
//src/Component.js
import moment from 'moment';
import 'moment-timezone';
```
to:
```
//src/Component.js
import moment from 'moment-timezone';
```

**Comment by pvoznyuk** [comment]
@ronnyandre @emersonbroga thanks for noticing that; Fixed in the latest release.
