### ISSUE TITLE
TimeZone not apply to date?

### ISSUE THREAD

**Issue by regisrc** [pvoznyuk/react-live-clock#103]
I need to output Qua, 5 Mai, 2021, based on my timeZone location (BR)
But it's showing Wed, May 5th, 2021, do this library don't change the location for days/months?
using 'ddd, MMMM Mo, YYYY' and
'America/Belem' timeZone

**Comment by anthony0030** [comment]
in react-live-clock@5.2.0 I added locale prop

**Comment by regisrc** [comment]
Hello, thanks for the fast answer
How can i use it? There's a doc about locale?

**Comment by regisrc** [comment]
Ok, i updated the lib but still not working 
![image](https://user-images.githubusercontent.com/47003717/120213230-56b30880-c209-11eb-835f-0157fe26003b.png)
Here's the clock code 
![image](https://user-images.githubusercontent.com/47003717/120213273-5e72ad00-c209-11eb-991a-873c011aa0f0.png)
The lib version
![image](https://user-images.githubusercontent.com/47003717/120213284-616d9d80-c209-11eb-8663-5b20b9b18221.png)
The output

**Comment by anthony0030** [comment]
Internally the clock uses moment.
Sometimes the language is not loaded automatically and needs to be loaded manually https://github.com/headzoo/react-moment#locale

What language are you trying to set? Portuguese?

**Comment by regisrc** [comment]
Yes im trying to set Portuguese-brazil (pt-br)

**Comment by regisrc** [comment]
![image](https://user-images.githubusercontent.com/47003717/120221810-69cbd580-c215-11eb-93b2-c7ee23a5e39a.png)
Ok, now it's working fine, thank for the support

**Comment by anthony0030** [comment]
Happy to help, thank you as well for helping me make this improvement.
