### ISSUE TITLE
Documentation mistake?

### ISSUE THREAD

**Issue by BrooklandKendall** [pvoznyuk/react-live-clock#129]
Nice utility, thanks.

In your documentation, I believe you mean Do where you have Mo.  

   <Clock
          date={'1997-12-31T14:15:23+01:00'}
          format={'dddd, MMMM Mo, YYYY, h:mm:ss A'} />

Mo is producing the month, whereas Do would produce the day.

**Comment by anthony0030** [comment]
Thanks for helping improve the utility! :)
