### ISSUE TITLE
Date is fixed at November 11, 2021

### ISSUE THREAD

**Issue by fdemello** [pvoznyuk/react-live-clock#135]
The current date is not being honored and seems to be fixed at November 11, 2021. See https://codesandbox.io/s/react-live-clock-date-bug-xwd5w as an example.

![image](https://user-images.githubusercontent.com/13694949/142922351-2a5edbe8-684b-46a3-ab05-44ea01c65ab4.png)

**Comment by anthony0030** [comment]
I think you just copied and pasted from the documentation.

There was a confusing part that was mentioned in #129.

November is the 11th month, there is no bug there.

Try 
```
"dddd, MMMM Do, YYYY HH:mm:ss"
```
 instead of 
```
"dddd, MMMM Mo, YYYY HH:mm:ss"
```
