### ISSUE TITLE
Feature Request: Set the ticking interval based on the smallest time unit in the formated date.

### ISSUE THREAD

**Issue by livelifelively** [pvoznyuk/react-live-clock#14]
Right now the time interval is 1 second. But if we refresh it based on the smallest time unit in passed format e.g. for "hh:mm" if we refresh every minute or less we can reduce frequency of dom update.

**Comment by anthony0030** [comment]
I will see what I can do.

**Comment by anthony0030** [comment]
Version 4.0.1-beta will address this problem.
