### ISSUE TITLE
Can I have ticking when using a custom date?

### ISSUE THREAD

**Issue by tytrdev** [pvoznyuk/react-live-clock#15]
I'm passing in a date that I'm basing on a gmtDifference value I have access to.

If I don't pass in a date and use ticking={true} I get the desired effect: the time is the current date and the ticking happens once per second.

If I DO pass in a date and use ticking={true}, I get no ticking effect.

**Comment by pvoznyuk** [comment]
Hi @ttracey93 
Let me investigate if I can help you.
Would you please provide a code example here if possible?

**Comment by zenio** [comment]
`<Clock date={'1997-12-31T14:15:23+01:00'} format={'HH:mm:ss'} ticking={true} />`

**Comment by pvoznyuk** [comment]
@ttracey93  @zenio this issue is fixed in `v3.0.0`,
You can take a look on the demo page, last example: https://pvoznyuk.github.io/react-live-clock/

**Comment by arifrdianto** [comment]
i have same issue, when passing props date no ticking effect

**Comment by anthony0030** [comment]
What version are you using?

**Comment by arifrdianto** [comment]
i'm using version 5.2.0

**Comment by arifrdianto** [comment]
but, i'm trying downgrade to `v4.0.5` ticking it's work for pass date custom

**Comment by anthony0030** [comment]
I don't have time to debug it at the moment, due to lots of work. But I will reopen the Issue.

**Comment by anthony0030** [comment]
This should be refixed in 5.5.0
