### ISSUE TITLE
locale as prop

### ISSUE THREAD

**Issue by ppjacome** [pvoznyuk/react-live-clock#164]
I'm trying to set another language on the component to set the day and Month on the right language.

Here's what I'm trying:

<Clock format={'ddd DD MMMM'} ticking={true} locale={'es'}/>

I hope someone can help me on seeing my mistake

**Comment by anthony0030** [comment]
I don't understand the question exactly. 
What output would you like from the component?

**Comment by anthony0030** [comment]
Closed due to no responce.
