### ISSUE TITLE
'blinking' prop only blinks last colon

### ISSUE THREAD

**Issue by tyler-a-eggert** [pvoznyuk/react-live-clock#177]
While the `blinking` property currently works fine if the format only has a single colon, e.g. `'h:mm a'`, when the format contains multiple colons, e.g. `'h:mm:ss a'`, only the last one blinks.
Is there a reason not all colons should be set to blink?

Further, is there a reason this property is not currently documented in the readme?

**Comment by anthony0030** [comment]
I added this option for you :)
just set blinking to ```all``` like this:
```<Clock blinking='all' format={'HH:mm:ss'} />```
