### ISSUE TITLE
Warning: Prop `dateTime` did not match. 

### ISSUE THREAD

**Issue by pelleadlen** [pvoznyuk/react-live-clock#180]
I added the clock to my next.js app, but in the console I get an error.

the error is like this 
 ```
Warning: Prop `dateTime` did not match. Server: "1653171979698" Client: "1653171980060"
    at time
    at n (webpack-internal:///./node_modules/react-moment/dist/index.js:11:16590)
    at ReactLiveClock (webpack-internal:///./node_modules/react-live-clock/lib/Component.js:30:24)
    at div
    at TimeZone
```
My component looks like this: 

```
   <Clock
        format={"h:mm A"}
        timezone={"Europe/Stockholm"}
        className="text-white text-2xl underline"
        ticking={true}

      />
```

Any ideas what's up?

**Comment by anthony0030** [comment]
Hi @pelleadlen, It looks like you are using server-side rendering. When the clock renders on the server some time passes till it renders again on the client causing the mismatch. I added a prop ```noSsr`` in version ```6..0.0``` this will prevent it from rendering on the server to fix this. It will add more renders to the component but you won't have the mismatch.

Please let me know ASAP if this is fixed for your situation. if not I will need more details.

**Comment by pelleadlen** [comment]
@anthony0030 It worked like a charm! thanks!

**Comment by anthony0030** [comment]
@pelleadlen, Happy to help!

**Comment by anthony0030** [comment]
You are correct, I don't see it anymore on NPM, I don't know what happened. Probably it failed to publish or got deleted somehow, I remember publishing it. I have a lot of things going on in my life at the moment :( I am happy you appreciate the work that has been put in.

**Comment by pelleadlen** [comment]
@domasrc In your package.json, try it like this:  "react-live-clock": "git://github.com/pvoznyuk/react-live-clock.git", 
Worked for me!

**Comment by anthony0030** [comment]
@pelleadlen Thank you for the tip! I did not know you can do that. :)
