### ISSUE TITLE
Timezone attribute not working

### ISSUE THREAD

**Issue by shanejones** [pvoznyuk/react-live-clock#184]
I'm currently using version `^6.0.0` along with `"moment-timezone": "^0.5.34"` and `"react-moment": "^1.1.2"`

When setting the timezone property like this 
`<Clock format="HH:MM" timezone="US/Pacific" ticking />`

it still shows my local time and I'm in the UK. I've tried a number of different timezones and none of them are loading with the specified timezomes.

**Comment by anthony0030** [comment]
if you take a look at the file ```node_modules/moment-timezone/data/meta/latest.json``` you can see the time zones that are there. there is a way to add other custom-named timezones in the documentation of that project. Also to get an American time zone you need to put ```America``` instead of ```US```

Examples:
```
"America/New_York",
"America/Detroit",
"America/Kentucky/Louisville",
"America/Kentucky/Monticello",
"America/Indiana/Indianapolis",
"America/Indiana/Vincennes",
"America/Indiana/Winamac",
"America/Indiana/Marengo",
"America/Indiana/Petersburg",
"America/Indiana/Vevay",
"America/Chicago",
"America/Indiana/Tell_City",
"America/Indiana/Knox",
"America/Menominee",
"America/North_Dakota/Center",
"America/North_Dakota/New_Salem",
"America/North_Dakota/Beulah",
"America/Denver",
"America/Boise",
"America/Phoenix",
"America/Los_Angeles",
"America/Anchorage",
"America/Juneau",
"America/Sitka",
"America/Metlakatla",
"America/Yakutat",
"America/Nome",
"America/Adak",
"Pacific/Honolulu"
```

If you need any more help, don't hesitate to ask :)

**Comment by shanejones** [comment]
I've just tested out `America/New_York` and it's still showing my local time in the UK.

**Comment by anthony0030** [comment]
Not to be the stereotypical works on my computer, Could you please provide your lock file. it is possible that you have multiple versions of your deps installed. 

This is working locally for me:
```
<Clock timezone="America/New_York" />
```

Please provide as much extra detail as you can please.
Have a great week!

**Comment by shanejones** [comment]
Sure @anthony0030 

My lockfile is attached here
[yarn.lock.txt](https://github.com/pvoznyuk/react-live-clock/files/8938294/yarn.lock.txt) 

I had to turn it into a .txt file to get it to upload here.

Thanks

**Comment by shanejones** [comment]
Yeah, I've tried a couple out of the list above and they are still coming out the same as my local time in the UK

**Comment by anthony0030** [comment]
Please try deleting your ```node_modules``` folder and redownloading it via ```Yarn``` or ```NPM```

**Comment by anthony0030** [comment]
Did this solve the problem you were having?

**Comment by shanejones** [comment]
That was something I tested a while ago. 

I've just jumped back onto this and spotted the problem. Wrong variable name coming from my API 🤣
Taking a break away from this helped me see the issue.

**Comment by anthony0030** [comment]
Happy to hear it is fixed :)
