### ISSUE TITLE
s.tz is not a function

### ISSUE THREAD

**Issue by RowanEdward** [pvoznyuk/react-live-clock#191]
After updating my package.json to the latest versions, I am not getting the below Error.

s.tz is not a function
./node_modules/react-moment/dist/index.js:11

    "react": "^18.1.0",
    "react-live-clock": "^5.7.0",
    "moment": "^2.29.4",
    "moment-timezone": "^0.5.34",
    "react-moment": "^1.1.2",

Is anyone else having a similar issue?

**Comment by tech-newurtopia** [comment]
+1

**Comment by tech-newurtopia** [comment]
> After updating my package.json to the latest versions, I am not getting the below Error.
> 
> s.tz is not a function ./node_modules/react-moment/dist/index.js:11
> 
> ```
> "react": "^18.1.0",
> "react-live-clock": "^5.7.0",
> "moment": "^2.29.4",
> "moment-timezone": "^0.5.34",
> "react-moment": "^1.1.2",
> ```
> 
> Is anyone else having a similar issue?

`"moment-timezone": "0.5.33",`
It's work for me

**Comment by RowanEdward** [comment]
I tried rolling back to version "moment-timezone": "0.5.33" but I am still getting the same Error.


react-dom.production.min.js:127 Uncaught TypeError: u.tz is not a function

**Comment by anthony0030** [comment]
Try deleting Node Modules and reinstalling them.

**Comment by TraderSamwise** [comment]
@RowanEdward 

updating moment dependency and downgrading moment-timezone worked for me. 

"moment": "^2.29.1"

**Comment by RowanEdward** [comment]
Rolling back to "moment": "^2.29.1" resolved the issue.
Thanks @TraderSamwise
