### ISSUE TITLE
react-fittext@1.0.0" has incorrect peer dependency "react@^15.0.0"

### ISSUE THREAD

**Issue by damiangreen** [pvoznyuk/react-live-clock#20]
Can the peer dependency be upgraded for react 16?

**Comment by damiangreen** [comment]
https://github.com/pvoznyuk/react-live-clock/pull/32

**Comment by anthony0030** [comment]
@pvoznyuk Any Update?

**Comment by damiangreen** [comment]
Will this be published to npm?

**Comment by anthony0030** [comment]
react-fittext is only for the demo page, that's why it is a dev dep.
