### ISSUE TITLE
Doesn't work with React 16.8. And it takes ages to install the package

### ISSUE THREAD

**Issue by akshayjp123** [pvoznyuk/react-live-clock#26]
`+ react-live-clock@3.1.0
added 666 packages from 278 contributors, removed 323 packages, updated 1273 packages, moved 4 packages and audited 36269 packages in 95.208s
found 63 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details`

**Comment by damiangreen** [comment]
I'm using 16.8.5 and it works.
