### ISSUE TITLE
Doesn't work with iOS devices.

### ISSUE THREAD

**Issue by jasonna2607** [pvoznyuk/react-live-clock#27]
Tested in both desktop and Android device, worked but when access it using my iPhone, shows invalid date instead.

Any workaround?

**Comment by anthony0030** [comment]
Please test with "react-live-clock": "^4.0.0-beta".
I did on my iPhone and it is working.
if it is not working, please provide the following information.

1) The browser you are using
2) The iPhone you are using
3) The version of IOS you are using 
3b) is the iPhone stock or jailbroken
4) A screenshot
5) Any errors on the safari remote console
