### ISSUE TITLE
NextJs Error: Prop `dateTime` did not match. 

### ISSUE THREAD

**Issue by Abdul-Asa** [pvoznyuk/react-live-clock#284]
Hello, I have a problem when using the react-live-clock with Nextjs app router.

In both development and production, I get warning errors in the console saying:
`Warning: Prop 'dateTime' did not match. Server: "1693165157072" Client: "1693165162962"`

The component renders and works as expected but is there a way to get rid of the warning? 
I suspected the component rendered on the server didn't match the client so I tried using the noSsr prop but that didn't get rid of it.
` <Clock
          className="italic font-hacker"
          format={"HH:mm A"}
          blinking
          ticking
          noSsr
        />`

I'm fairly new to SSR frameworks so I'm not sure if this is a caused by nextjs, react-live-clock or just my mistake. 
I'm running the lateest version of nextjs and react-live-clock and my component is in a server component.
I'd appreciate any feedback or solution to get rid of the warning.

**Comment by igoreznik** [comment]
I have this issue too, I would like a solution too.

**Comment by anthony0030** [comment]
it is possible that ```document``` is defined on the server. in that case, the ```noSsr``` option will not work. 
Could you please check to see if this is the case? possibly I can change the code to also check for window. is window defined on the server?

**Comment by igoreznik** [comment]
My issue is that I want the SSR, I am using Next js, but I have the hydration warning, How can I avoid this warning and use the SSR?

**Comment by Abdul-Asa** [comment]
> it is possible that `document` is defined on the server. in that case, the `noSsr` option will not work. Could you please check to see if this is the case? possibly I can change the code to also check for window. is window defined on the server?



> it is possible that `document` is defined on the server. in that case, the `noSsr` option will not work. Could you please check to see if this is the case? possibly I can change the code to also check for window. is window defined on the server?

No, I don't think so. I get an error when trying to access window or document objects in server components.

**Comment by anthony0030** [comment]
You will have the hydration warning because when it renders on the server it's a different time than when it renders in the browser. the noSsr option is to prevent it from rendering on the server. In that way, there are no different props. 

Here is a resource: https://nextjs.org/docs/messages/react-hydration-error

**Comment by Abdul-Asa** [comment]
After much consideration, I've decided to wrap the component in a client component so it only renders on the browser. This solves the issue and gets rid of the warning. Not really a proper solution but it works fine for me. 
Thanks for the  replies and shared resources @anthony0030.

**Comment by anthony0030** [comment]
Hi @Abdul-Asa could you please share the implementation you came up with to help others in the future and to possibly aid in development?

**Comment by Abdul-Asa** [comment]
Sure. Here's how I wrapped it.
` 
'use client'
const ClientClock = () => {
  return (
     <Clock
              className="italic font-hacker"
              format={"HH:mm A"}
              blinking
              ticking
              noSsr
            />
  );
};
`

and then imported as

`
\\...
import ClientClock from './ClientClock'
....
return(
...
<ClientClock/>
)
`

**Comment by anthony0030** [comment]
hi @Abdul-Asa Thanks for the code example. I did not know about the directive ```'use client';``` in JS. I have implemented it in version ```6.1.16```. I think this will help in general! Thanks again.
