### ISSUE TITLE
Is there a way to localize the clock?

### ISSUE THREAD

**Issue by bjacquemet** [pvoznyuk/react-live-clock#29]
The default clock is in EN format. 
Is there a way with moment to change the locale?

Thanks!

**Comment by anthony0030** [comment]
```
import moment from 'moment-timezone';
moment.locale('el');
````

OR 

```
import moment from 'moment';
moment.locale('el');
````

Both seem to work for me.

Please try "react-live-clock": "^4.0.0-beta"
