### ISSUE TITLE
locale prop not changing day and month abbreviation

### ISSUE THREAD

**Issue by culliard** [pvoznyuk/react-live-clock#320]
I have the following code:
`<Clock format={'ddd DD MMM HH:mm'}`

which displays the following in English as expected 
`Thu 20 May 12:18`

If I change the locale via the prop, I would expect the abrreviation for day and month to change to German equivalents, but it doesn't. I think this is what this [issue](https://github.com/pvoznyuk/react-live-clock/issues/164) is getting at.

In my case I'm using German and I've used May as the month for this example, as Jun is the same in both. 

`<Clock format={'ddd DD MMM HH:mm'} locale={'de'}/>`

Expected output:
`Do 20 Mai 12:18`

I'm using version 6.1.22. Am I doing something wrong?

**Comment by anthony0030** [comment]
If you are changing the locale on the fly the example named "Change the language on the fly" would help you.
I added some code for you in version ```6.1.23-beta``` that I would like you to test for me, please.
If it works I will make the change not beta.

**Comment by culliard** [comment]
Thanks for prompt response.

I should have stated that I wasn't changing the locale on the fly. I restarted it with the locale fixed to 'de' which made no difference.

I tested 6.1.23-beta which didn't appear to help. After some further research and testing I found that simply adding the following to my code, made it work!

`import 'moment/locale/de';`

Now that I figured that out, 6.1.23-beta works perfect when changing locale on the fly with the following:
`<Clock format={clockFormat} ticking={true} key={key} locale={getLocale()}`

I'm satisified I found a workaround - for now you could mention this in your usage docs, or as an improvement somehow dynamically import the moment locale when the component first loads, or when locale is changed.

Thanks

**Comment by anthony0030** [comment]
I imported moment like this ```import moment from 'moment-timezone';```

This here might be helpful: https://stackoverflow.com/a/52559157



>Usually the list of supported application languages is limited, so it's unreasonable to load all available Moment locales because of increased footprint.
>Moment package contains prebundled locales for this purpose. E.g:
> ```import moment from 'moment';```
> ```import 'moment/min/locales';```
Or:
> ```import moment from 'moment/min/moment-with-locales';```


I can see how importing moment differently will impact the locales available
