### ISSUE TITLE
Changing moments local doesn't affect Clock

### ISSUE THREAD

**Issue by js-chris** [pvoznyuk/react-live-clock#34]
Hi,

if you change moments locale globally on the fly (moment.locale('de')), Clock is not changing it's format. 

So if you use a format like 'ddd DD. MMMM, HH:mm', the format stays on the locale initially loaded.

Thanks
Chris

**Comment by anthony0030** [comment]
Please test with: "react-live-clock": "^4.0.0-beta", 
This is working for me:
```
<Clock format={'HH:mm:ss a'} />
<br />
<button onClick={() => moment.locale('el')}>
  Make it Greek!
</button>
```

**Comment by ppjacome** [comment]
If you change the format such as:
<Clock format={' dddd DD, MMMM  '} ticking={true} />
 <button onClick ={() => moment.locale('el')}>Greek</button>

it's not working
