### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by tofikabdullayev** [pvoznyuk/react-live-clock#36]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ReactLiveClock (at TimeBox/index.tsx:20)

**Comment by anthony0030** [comment]
I haven't forgotten about this Issue.
I haven't fount a good solution yet.
Any PR to fix this is welcome! :)

**Comment by tofikabdullayev** [comment]
what about unsubscribe on `componentWillUnmount` hook ? :)

**Comment by anthony0030** [comment]
I found a fix, and I made a fix. I asked @pvozniuk to publish the new version (4.0.4).
If you have any problem I am here to help.

**Comment by tofikabdullayev** [comment]
thanks!

**Comment by damiangreen** [comment]
We've just hit this one. 

When will the npm package be released?

**Comment by anthony0030** [comment]
I emailed the developer.

Bump @pvoznyuk :)

**Comment by AmineBlel** [comment]
Still got the same problem when I use the component in different pages, Has the npm package been released?

**Comment by sig-dan** [comment]
@AmineBlel @anthony0030v @pvoznyuk I can confirm this is still happening with the latest releases
