### ISSUE TITLE
[Feature Request] Add blink to the colon to indicate pass of time

### ISSUE THREAD

**Issue by asvrada** [pvoznyuk/react-live-clock#37]
Could you add a boolean property `blink` that controls if the colon blinks every half interval?

If `blink==false`, then this component works like without this feature.
If `blink==true`, and assume `interval==1000`, then the colon would toggle every `interval/2` millisecond:

For example current time is 10:24:33

| Time 0    | 10:24:33 |
|-----------|----------|
| Time 500  | 10:24 33 |
| Time 1000 | 10:24:34 |
| Time 1500 | 10:24 34 |
| Time 2000 | 10:24:35 |

PS: If the output time format is HH:MM, then blink that colon instead.

**Comment by anthony0030** [comment]
Thank you for request. I will see how I can implement this as soon as I can.

**Comment by anthony0030** [comment]
I have tried to implement this before my computer started having problems.
I was unsuccessful in making this work. I will try in the future again.

**Comment by anthony0030** [comment]
Good morning @asvrada :)

I implemented this in version 5.0.0-beta1 Especially for you, sorry for the long delay.

Take a look and tell me if it makes your dream come true.


All the best Anthony
