### ISSUE TITLE
how can i fix useEffect clean up error?

### ISSUE THREAD

**Issue by choiwono** [pvoznyuk/react-live-clock#38]
Error message :
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

how can i fix this problem?

**Comment by anthony0030** [comment]
Take a look at the commits I made in this repo.
I refactored the code and now we wait for the owner to push it up to NPM.

Have a great day!
