### ISSUE TITLE
unmount live clock

### ISSUE THREAD

**Issue by bijaybdrkarki** [pvoznyuk/react-live-clock#39]
i used this (react-live-clock) component inside my home.js component of App.js, but when i change route, react throws and error about react update of unmount component. 
to solve it i tried using useEffect hook:

```
const [timeclock , settimeclock] = useState([]); 
   
    useEffect(() => {
        time();
        
},[]);
const time = async ()=> {
    
    const data =  (<Clock  format={'HH:mm:ss A'} ticking={true} timezone={'America/Toronto'} />)
    
    settimeclock(data);
    
}
```
but still this throws error
<img width="449" alt="Screen Shot 2020-04-02 at 14 31 19" src="https://user-images.githubusercontent.com/37946823/78296356-9003c180-74fb-11ea-9dec-c896589692b4.png">

**Comment by anthony0030** [comment]
What version of the script are you using?

**Comment by bijaybdrkarki** [comment]
<img width="416" alt="Screen Shot 2020-04-03 at 13 54 55" src="https://user-images.githubusercontent.com/37946823/78390544-bf293a00-75b2-11ea-9469-47067109fe28.png">

**Comment by anthony0030** [comment]
I fixed this problem.
I am waiting for the owner of the repository to push up the fix
https://github.com/pvoznyuk/react-live-clock/blob/master/CHANGELOG.md
