### ISSUE TITLE
React 17 Support

### ISSUE THREAD

**Issue by jarojasm95** [pvoznyuk/react-live-clock#70]
```
npm ERR! While resolving: mc_webapp@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8" from react-live-clock@5.0.12
npm ERR! node_modules/react-live-clock
npm ERR!   react-live-clock@"5.0.12" from the root project
```

**Comment by anthony0030** [comment]
Please check if version 5.0.13 fixed this :)

**Comment by jarojasm95** [comment]
It's not fixed, but now the conflict is coming from https://github.com/headzoo/react-moment

**Comment by anthony0030** [comment]
What problem are you facing exactly? Could you please specify the problem, and provide one or all of the following:
1) Screenshot
2) Error Logs
3) Minimum setup that reproduces the problem

**Comment by anthony0030** [comment]
Please check version 5.0.16
