### ISSUE TITLE
TimeZone clock is not changed according to timezone prop.

### ISSUE THREAD

**Issue by maoryadin** [pvoznyuk/react-live-clock#76]
Clock is not recalculate to new Time Zone after propery timeZone is change dynamically.

Example:

locale = 'Australia/Sydney'
after oneMinute i am setting new TimeZone:

locale = 'Europe/London'

but the Clock component not changing the time based on the new zone.

`<Clock className="world_clock__item" format={format} ticking={true} timezone={locale}/>`

**Comment by anthony0030** [comment]
What version are you using of the package and react?

**Comment by maoryadin** [comment]
> What version are you using of the package and react?

Just upgrade from version 4.x and it was solved.
