### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by maoryadin** [pvoznyuk/react-live-clock#78]
I have error that happening only in production.

Operation systems difference:

dev - windows.
production - linux.

tnx for any help 

![typeError](https://user-images.githubusercontent.com/31710467/104836693-5c422e80-58b8-11eb-922c-c39f20773604.png)

![Untitled1](https://user-images.githubusercontent.com/31710467/104836740-ab885f00-58b8-11eb-8162-196b86e9647d.png)

![Untitled](https://user-images.githubusercontent.com/31710467/104836867-8b0cd480-58b9-11eb-87c2-d7d229da034f.png)

**EDIT:**

Solved by downgrade react-live-clock to version 4.0.5.

react-live-clock version 5.0.13 have a dependency on "react-moment": "^1.1.1"

and this one make it not working on produciton.
its a bug.

**Comment by maoryadin** [comment]
Solved by downgrade react-live-clock to version 4.0.5.

From some reason version 5.0.13 is dependency on     "react-moment": "^1.1.1",

and this one make it not working on produciton.
its a bug.

**Comment by maoryadin** [comment]
Problem occurs when react-moment is on version 1.1.1 or 1.1.0.
Fixed by downgrade react-moment to version 0.9.7.

**Comment by anthony0030** [comment]
Thanks for your time.
It would be a good idea to open an issue with react-moment/
