### ISSUE TITLE
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.     in ReactLiveClock

### ISSUE THREAD

**Issue by jeynergil** [pvoznyuk/react-live-clock#80]
Hi, 

This is a wonderful plugin.
I have used this. It works well except when I click the back button on the browser, it will throw this:

`Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ReactLiveClock`

I am using Class component. May I know how to fix this?

Thank you.

**Comment by anthony0030** [comment]
Thank you for your feedback. Are you running the latest version (5.0.13)?

**Comment by jeynergil** [comment]
Thank you for the reply.

I am running 4.0.5. I'll update and let you know of the results.

**Comment by jeynergil** [comment]
I have updated. Seems like it is working.
