### ISSUE TITLE
Unable to Use

### ISSUE THREAD

**Issue by LP-Codes** [pvoznyuk/react-live-clock#96]
Hello,
 i m getting below error though timezone is installed
 /node_modules/react-live-clock/lib/Component.js
Module not found: **Can't resolve 'moment-timezone'** in 'D:\testmode\node_modules\react-live-clock\lib'

**Comment by LP-Codes** [comment]
uninstalling & reinstalling  moment-timezone & this package fixed it ..

**Comment by anthony0030** [comment]
Happy you able to fix it.
