### ISSUE TITLE
No `filter` prop?

### ISSUE THREAD

**Issue by exoRift** [pvoznyuk/react-live-clock#99]
The README speaks of a `filter` prop but I checked the source code and it doesn't even seem to exist?

**Comment by anthony0030** [comment]
Thank you for your feedback!
When I made version 5 I forgot to add it back.
Please see if version 5.1.0 serves you.

**Comment by yahyayoga** [comment]
Hello, I get the same problem on version 6.1.1
![image](https://user-images.githubusercontent.com/19502291/207776142-798b7121-a167-4c32-9f39-aae7a651687e.png)
I checked the code, the filter prop is empty 
![image](https://user-images.githubusercontent.com/19502291/207776308-b3073431-1f81-4aaa-a3c8-50f647152f92.png)
am I missing something?
